version: '3.3'

services:
  bot:
    container_name: vendetta-bot
    build:
      context: .
    working_dir: "/usr/src/app/vendetta-bot"
    volumes:
      - .:/usr/src/app/vendetta-bot
      - postgresDB:/var/lib/postgres
    command: python3 -m bot
    env_file:
      - ".env"
    networks:
      tg:

volumes:
  postgresDB:

networks:
  tg:
